### ISSUE TITLE
RDTSC limitations

### ISSUE THREAD

**Issue by ocramz** [tonyday567/perf#8]
The more I read about it, the more of a minefield it looks, e.g https://www.strchr.com/performance_measurements_with_rdtsc says:

> The scope of the method
>     This method is useful for measuring the tasks that are mostly computation-bounded, 
> e.g. various calculations, cryptographic functions, fractal generation, some text-processing tasks, etc.
>     Your data should be located in L1 or L2 cache entirely. If you are measuring memcpy function 
> for several megabytes of data, you should use a different method. 
> Ditto for most image-processing functions and other memory-intensive tasks.
>     If your task involves reading or writing files, calling "heavy" API functions, you should use 
> a different method.
>     This method is ideal if you have a simple function that is called very often, doesn't call any 
> API functions, and operates on a small data set.

**Comment by ocramz** [comment]
As I understand it, timing measurements have to be calibrated to understand what's a typical reading. `perf` for small computations and something like `criterion` for longer-running ones.

**Comment by tonyday567** [comment]
All of those issues you quote apply equally to both short and long-run processes - if there's context switches and GC activity and such, these will show up no matter what method you use.  I would back `perf`-style method over `criterion` no matter the length or complexity.  Except if you want a solid library,, then go with criterion.

That's not to say that the library is robust yet - just that criterion leaves a lot on the table when it comes to understanding what's going on.  `perf` is leaving a lot on the table as well, but because I could never find low-level c code for the RDPMC chip.

https://github.com/nh2/haskell-cpu-instruction-counter is a very similar recent effort, but i don't have a linux box.

**Comment by ocramz** [comment]
This SO answer deals with interacting with RDPMC from C : https://stackoverflow.com/questions/22309041/rdpmc-in-user-mode-does-not-work-even-with-pce-set . Also, I'm thinking of doing some surgery on criterion as well, pulling out Criterion.Measurement and its dependencies (minus the `statistics`, `js-*`, `microstache` and `optparse-applicative` bits) into a standalone package: https://github.com/bos/criterion/issues/189

**Comment by tonyday567** [comment]
What are you looking for in criterion?  There's not much in Criterion.Measurement,, it's pretty much a coarse wrapper around GHC.Stats.  If you take out statistics then you're ditching the outlier analytics that the library rests on.  whnf, nf and friends are important, and contain a great deal of battle-hardened knowledge about stopping memoization. But their related context - Benchmarkable - swallows the original type being benchmarked, and this is why I went with a new library rather than used criterion: you can't write Benchmarkable as a logger/ReaderT/continuation.

**Comment by tonyday567** [comment]
> This SO answer deals with interacting with RDPMC from C : https://stackoverflow.com/questions/22309041/rdpmc-in-user-mode-does-not-work-even-with-pce-set .

```
#include <linux/module.h>   /* Needed by all modules */
#include <linux/kernel.h>   /* Needed for KERN_INFO */
```

This was the show-stopper for me when I tried to hack this up: I wanted an osx solution and it proved difficult to port
